### ISSUE TITLE
wordpress.com blocked

### ISSUE THREAD

**Issue by shoeper** [stonecrusher/filterlists-pihole#3]
Starting with the following commit wordpress.com is completely blocked:

https://github.com/stonecrusher/filterlists-pihole/commit/b29162dcd41eea7ba63acbb44b79aca96bfa41c0#diff-cd5ad54b01aba5c9ab12ad5a84b4394c09260955810a6ea7c5b83aacddfb9929R17285

**Comment by stonecrusher** [comment]
Oh wow, needs immediate fix.
It is because watchlist-internet added a subdomain of wordpress but we only block domains as a whole to ensure compability with different blocker approaches (not only pihole).
Thank you for the report.

https://github.com/stonecrusher/filterlists-pihole/commit/195ff76e91f7188b8f8e09019d2b83ba8fb21e56

**Comment by shoeper** [comment]
Thanks, I appreciate your efforts.
